

export const SET_ALL_COMMENT='SET_ALL_COMMENT';



export const FETCH_ALL_COMMENT_API= 'FETCH_ALL_COMMENT_API';
export const ADD_COMMENT_API='ADD_COMMENT_API';
export const DELETE_COMMENT_API='DELETE_COMMENT_API';
export const UPDATE_COMMENT_API='UPDATE_COMMENT_API'