
export const SET_ALL_PROJECT='SET_ALL_PROJECT'
export const SET_EDIT_PROJECT='SET_EDIT_PROJECT'
export const SET_PROJECT_DETAILS='SET_PROJECT_DETAILS'

/*****************************Saga***************************** */
export const CREATE_PROJECT_API='CREATE_PROJECT_API'
export const FETCH_ALL_PROJECT_API='FETCH_ALL_PROJECT_API'
export const UPDATE_PROJECT_API='UPDATE_PROJECT_API'
export const DELETE_PROJECT_API='DELETE_PROJECT_API'
export const ASSIGN_USER_API='ASSIGN_USER_API'
export const REMOVE_USER_FROM_PROJECT_API='REMOVE_USER_FROM_PROJECT_API'
export const FETCH_PROJECT_DETAIL_API='FETCH_PROJECT_DETAIL_API'
export const CREATE_TASK_API="CREATE_TASK_API"

