export const SET_TASKTYPE="SET_TASKTYPE"


export const FETCH_ALL_TASKTYPE_API="FETCH_ALL_TASKTYPE_API";
export const UPDATE_TASK_API="UPDATE_TASK_API";
export const HANDLE_CHANGE_POST_API="HANDLE_CHANGE_POST_API";
export const UPDATE_TASK_STATUS_API="UPDATE_STATUS_API"